canonical/kubeflow-ci

- releases/1.4/kubeflow-bundle.yaml
- releases/1.4/mlflow.yaml
- releases/1.4/spark.yaml
Add custom yaml field `_github_repo_name` to indicate where the source code lives for each charm.
I didn't add `_github_repo_name` field for charmed-osm-mariadb-k8s because I don't know where it lives and we are not going to create a branch on their repo.
Github apis follow the following format:
`https://api.github.com/repos/{github_repo_owner}/{github_repo_name}/...`
It requires less data cleaning in the script to store repo owner and repo name separately.
So far, all of the repos are under `Canonical`. Therefore, only `_github_repo_name` field is added.
In the future, the script could be easily extended to support a `_github_repo_owner` field.
> add custom yaml field for github repo name

- tox.ini
When executing the script the environment variable is currently not passed through to tox. This minor change will allow that for the branch automation script exclusively.
> Pass bot token Environemnt variable through tox.

- releases/1.4/mlflow.yaml
Uses track in charmhub of `ch:1.13` instead of `ch:1.13.1`
> pin mlflow-server channel to minor version

- releases/1.6/kubeflow-bundle.yaml
- releases/1.6/mlflow.yaml
- releases/1.6/spark.yaml
- tox.ini
This PR adds the bundle files for the kubeflow 1.6 release that pull from each charm's invidual track in the edge risk.
> Add kubeflow bundle for 1.6 using tracks and edge risk

- releases/1.6/kubeflow-bundle.yaml
metacontroller-operator is now updated to 2.0. Please do not merge this PR before the track has been created. 
Follow [this](https://discourse.charmhub.io/t/request-add-track-2-0-to-metacontroller-operator/6895) thread for status updates.
> fix: corrects metacontroller-operator track version 0.3->2.0

- releases/1.6/kubeflow-bundle.yaml
Forgot about the kind option in the 1.6 releases directory.
> Add kind option to istio-ingressgateway

- releases/1.6/kubeflow-bundle.yaml
oidc-gatekeeper -> ckf-1.6/edge
> changes on bundle definition to match canonical/bundle-kubeflow

- .github/workflows/on_pull_request.yaml
- pyproject.toml
- scripts/release-charms/README.md
- scripts/release-charms/create_release_workflow_dispatch_manifest.py
- scripts/release-charms/requirements.txt
- scripts/release-charms/test_workflow_dispatcher.py
- scripts/release-charms/workflow_dispatcher.py
- tox.ini
Adds workflow_dispatcher.py and create_release_workflow_dispatch_manifest.py which together make it easier to release multiple charms from one channel to another at once.  See the included README.md for usage instructions
NOTE:
* this PR depends on additional features [added to chisme](https://github.com/canonical/charmed-kubeflow-chisme/pull/27).  At the moment, you must have them locally and edit the requirements.txt file to reference your local copy
Test instructions:
* get a local version of the above chisme PR and add to your requirements.txt file, as mentioned above
* use `tox -e test_batch_release_charms`
Todo before merging:
> add scripts for batch releasing charms

- cannon_runs/2022-08-31_batch_bump_versions/README.md
- cannon_runs/2022-08-31_batch_bump_versions/main.sh
- cannon_runs/2022-08-31_batch_bump_versions/repos.txt
- cannon_runs/2022-08-31_batch_bump_versions/run_git-xargs.sh
This is a batch operation using git-xargs to apply sed across our repos and bump common image versions.  Typical use would be to bump from one RC to another.
See README.md for more details
> add a batch operation for bumping image versions

- tests/1dot6/requirements.txt
It's previous setting >=2 does not match any released version of kfp, causing the tests to fail.
NOTE: At the moment this library isn't being used by the 1dot6 ci. Don't remove it since it very likely will be in the future
> [JUJU-1843] Set kfp requirement for 1dot6 to <2

- tox.ini
This will allow users to pass in a custom kubeconfig to Lightkube via this envvar, instead of always using ~/.kube/config
> [JUJU-1843] Add KUBECONFIG to passenv

- scripts/images/get-all-images.sh
Script was called with $REPO prepended. After re-design this should have been removed.
- Removed not needed $REPO fron script call.
> fix: updated script call to ensure proper execution

- .github/workflows/sync_charmstore_credentials.yaml
This PR should have been done when new repositories were added to CKF.
- Added two new repositories to sync workflow. It is required to propagate charmcraft credentials to new repositories.
> fix: added two new repositories to sync

- .github/workflows/workflows.md
Previously, the charmcraft credential sync instructions suggested using the default `charmcraft login` ttl, which is about 30 hours.  This updates it to ~6 months.
> Update workflows.md with longer ttl

- actions/dump-charm-debug-artifacts/logdump.bash
Fix `logdump` issue that prevents Charmcraft logs from being collected as part of the relevant CI action. This was due to the provided path not being extended as desired in the `logdump` bash script. More details in the linked issue.
Closes #92
> fix: Collect Charmcraft logs as part of CI action

- scripts/images/get-all-images.sh
GH runners are running out of space. Need to add cleanup of interemediate, not needed artefacts.
- Added removal of repositories to save space.
- Removed not needed debug logs.
> fix: save space

- scripts/images/get-all-images.sh
- scripts/images/scan-images.sh
- Removed debug log.
- Added removal of all containers.
> fix: logs and cleanup

- scripts/images/get-summary.py
- scripts/images/scan-images.sh
CVE scanner script produces a report with counts of CVEs per severity. Trivy report provide Class of the target for which CVE was detected. There are two classes `os-pkgs` and `lang-pkgs`. This PR contains changes that generate CVE report per class.
This will allow more accurate analysis of CVEs.
- Added script that generates CVE count summary per class, i.e. for OS and LANG packages classes in Trivy reports.
- Modified main shell script to properly format report and call new script.
NOTE: When scanner cannot identify base image it is indicated as `N/A`. This is the case for ROCK images.
Testing new format:
```
IMAGE,BASE,CRITICAL,HIGH,MEDIUM,LOW,CRITICAL-OS,CRITICAL-LANG,HIGH-OS,HIGH-LANG,MEDIUM-OS,MEDIUM-LANG,LOW-OS,LOW-LANG …
```
> Feat summary per class script

- scripts/images/scan-images.sh
Scan images script is used in GH workflow that reply on job's directory structure. This script needs to be updated to make it suitable  for use in workflows.
Issue and solution is described in https://github.com/canonical/bundle-kubeflow/issues/667
- Removed call to get-summary.py from scan-images.sh to enable independent use of scripts in workflows.
NOTE: Workflows might need to change to use scripts separately. Eg. https://github.com/canonical/bundle-kubeflow/pull/666
> fix: update scan images script

- actions/dump-charm-debug-artifacts/action.yml
Currently, the logdump action output path is hard-coded. Running this action twice in the same CI causes these actions to overwrite each others logs.
With this commit, the path can now be configured by setting the `$LOGDUMP_OUTPUT_DIR` env variable in a workflow. If it is not set the path will fall-back to `tmp_logs_$GITHUB_JOB` with $GITHUB_JOB being the unique id of the current running job.
Closes #95
> Make logdump action output path configurable

- actions/dump-charm-debug-artifacts/action.yml
Use `$HOME` instead of hardcoded `/home/runner` in order to be compatible 
with self-hosted runners too. Details in the issue below.
Fixes https://github.com/canonical/kubeflow-ci/issues/115
> Update dump-charm-debug-artifacts to use `$HOME`

- .github/workflows/on_pull_request.yaml
To keep consistency with the CKF owned repositories, we must pin the juju version to 3.1/stable, and install microk8s in strict mode to allow bootstraping juju 3.x controllers. This commit also pins microk8s to v1.25.
Fixes [this issue](https://github.com/canonical/kubeflow-ci/actions/runs/7614294450/job/20736238273#step:3:223)
> ci: use microk8s strict and pin juju version

- .github/workflows/sync_charmstore_credentials.yaml
Adds the repo https://github.com/canonical/ngc-integrator-operator to `sync_charmstore_credentials.yaml`
> feat: add ngc-integrator-operator to sync_charmstore_credentials.yaml

- .github/workflows/on_pull_request.yaml
Part of canonical/bundle-kubeflow#944
> ci: use juju 3.4/stable instead of 3.5/stable

- .github/workflows/sync_charmstore_credentials.yaml
The canonical/namespace-node-affinity-operator repository was missing from this list.
> ci: add canonical/namespace-node-affinity-operator to sync workflow

- scripts/cve-reports/README.md
- scripts/cve-reports/send-scan.py
Added:
* GitHub metadata to request - usefull when having multiple repos
* Verbosity flag printing request  body and response code
KU-1194
> Update send-scan.py with gh meta and verbosity

- scripts/images/get-all-images.sh
- scripts/images/get-images.sh
- scripts/images/scan-images.sh
Refs https://github.com/canonical/bundle-kubeflow/issues/1030
The current scanning action is failing because the bash script for gathering the image is failing, but the whole step is not failing
https://github.com/canonical/bundle-kubeflow/actions/runs/10482022617/job/29032456143#step:6:13
```
Error: open releases/1.9/stable/kubeflow/bundle.yaml: no such file or directory
Error: open releases/1.9/stable/kubeflow/bundle.yaml: no such file or directory
Image list:
```
This PR adds `set -xe` to all the bash scripts, to ensure they will exit if any of their sub-commands exits prematurely
> Use "set -xe" for exiting on errors

- scripts/images/scan-images.sh
This is a workaround for https://github.com/aquasecurity/trivy-action/issues/389
This change has been tested [here](https://github.com/canonical/bundle-kubeflow/actions/runs/11114666190) pointing to the branch of this PR. A way to test w/o the fix would be to run the "Scan images" workflow from `main` or observe the failure.
Fixes canonical/bundle-kubeflow#1080
> fix: pass --db-repository option to scanner

- scripts/images/scan-images.sh
This is a workaround for aquasecurity/trivy-action#389
Fixes canonical/bundle-kubeflow#1080
This change has been tested [here](https://github.com/canonical/bundle-kubeflow/actions/runs/11226285214) pointing to the branch of this PR. A way to test w/o the fix would be to run the "Scan images" workflow from `main` or observe the failure.
> fix: pass java-db-repository option to the scanner

- .github/workflows/on_pull_request.yaml
* Bump juju to 3.6/stable
* For uniformity, use charmcraft from 3.x/stable
Ref canonical/bundle-kubeflow#1176
> ci: bump juju to 3.6 + charmcraft to 3.x/stable

- actions/dump-charm-debug-artifacts/README.md
- actions/dump-charm-debug-artifacts/action.yml
Since v4 of the upload-artifact, artifacts are immutable. Thus, 
enable optional input `artifact-prefix` in order to avoid uploading logs
from different jobs to the same artifact. This input is neccesary when
the action is being called multiple times for the same job using a
matrix. On top of that, always prefix the artifact with the job name.
Fix #152
Tested in https://github.com/canonical/kfp-operators/pull/661, the created artifacts should be accessible here https://github.com/canonical/kfp-operators/actions/runs/12985907043.
> fix: Prefix artifact name with job name and run id

- .github/workflows/sync_charmstore_credentials.yaml
Part of https://github.com/canonical/bundle-kubeflow/issues/1207
> chore: add feast-operators repo to sync charmcraft creds

- .github/workflows/sync_charmstore_credentials.yaml
Since Velero is now usable for taking backups, and is owned by Kubeflow Charmers
https://charmhub.io/velero-operator
> chore: add velero operator for charmcraft credentials

- .github/workflows/sync_charmstore_credentials.yaml
- .github/workflows/sync_github_token.yaml
Closes #147 
Renames `PAT_TOKEN` secret to `GH_TOKEN` for consistency across repos.
Note to reviewer: temporarily set to run on pull request so a dry run is triggered in the CI as a test, see [this run](https://github.com/canonical/kubeflow-ci/actions/runs/17094360965/job/48475200241?pr=172). Will remove before merging.
> feat: create workflow to sync `GH_TOKEN` to rock repos
